spring:
  datasource:
    platform: ${DATABASE_PLATFORM}
    driverClassName: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  application:
    name: song-service

server:
  port: 8010